[package]
name = "colorpicker"
version = "3.0.0"
description = "Your powerful toolkit for mastering colors."
authors = ["Toinane <hello@crea-that.fr>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.2", features = [] }
tauri-utils = "2.0"
tauri-plugin-log = "2.0"
tauri-plugin-single-instance = "2.0.0"
log = "0.4"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "sync"] }

[target."cfg(target_os = \"windows\")".dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_System_LibraryLoader",
] }

[target."cfg(target_os = \"macos\")".dependencies]
core-graphics = "0.24"
core-graphics-types = "0.2"
core-foundation = "0.10"
foreign-types = "0.5"
cocoa = "0.25"
objc = "0.2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
