[package]
name = "colorpicker"
version = "3.0.0"
description = "Your powerful toolkit for mastering colors."
authors = ["Toinane <hello@crea-that.fr>"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.6", features = [] }

[dependencies]
tauri = { version = "2.11", features = ["tray-icon"] }
tauri-utils = "2.9"
tauri-plugin-log = "2.9"
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-store = "2.4"
tauri-plugin-global-shortcut = "2.3"
log = "0.4"
chrono = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "sync"] }
tauri-plugin-autostart = "2.5.1"
tauri-plugin-window-state = "2.4.1"
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-notification = "2.3.3"

[target."cfg(target_os = \"windows\")".dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common",
    "Win32_System_LibraryLoader",
] }

[target."cfg(target_os = \"macos\")".dependencies]
core-graphics = "0.24"
core-graphics-types = "0.2"
core-foundation = "0.10"
foreign-types = "0.5"
cocoa = "0.25"
objc = "0.2"
metal = "0.29"
core-text = "20.1"
block = "0.1"
objc-foundation = "0.1"
objc_id = "0.1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
