name: Building Colorpicker Nightly App

on:
    pull_request:
        branches:
            - dev

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 15

            - name: apt-get update on Ubuntu
              run: sudo apt-get update
              if: matrix.os == 'ubuntu-latest'

            - name: install dependencies
              run: yarn install --frozen-lockfile

            - name: add rimraf dependency
              run: yarn add rimraf

            - name: build Colorpicker Nightly
              run: npm run release

            - name: test to remove
              run: ls ./release

            - name: Cleanup artifacts
              run: shopt -s extglob && rm -rf release/!(*.exe|*.msi|*.deb|*.rpm|*.AppImage|*.dmg|*.snap)
              if: matrix.os != 'windows-latest'

            - name: Cleanup Windows artifacts
              run: for /f %F in ('dir /b /a-d ^| findstr /vile ".exe .msi"') do del "%F"
              if: matrix.os == 'windows-latest'

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.os }}
                  path: release
